import type { CinematicSequence } from '@/types/cinematic'

// Timeline mestre: 0 = topo da página, 1 = final
// Cada sequência mapeia um trecho da jornada narrativa
export const cinematicSequences: CinematicSequence[] = [
  {
    id: 'opening-caos',
    title: 'Caos operacional — fragmentos dispersos',
    start: 0.00,
    end: 0.04,
    cameraPath: 'idle-front',
    activeObjects: ['fragments', 'alerts', 'voxels'],
    quality: 'high',
    reducedMotionFallback: 'skip',
    color: '#ef4444',
    intensity: 1.0,
  },
  {
    id: 'opening-detection',
    title: 'Detecção — pulso azul varre o caos',
    start: 0.04,
    end: 0.08,
    cameraPath: 'idle-front',
    activeObjects: ['fragments', 'alerts', 'scan-wave', 'voxels'],
    quality: 'high',
    reducedMotionFallback: 'skip',
    color: '#3b82f6',
    intensity: 1.0,
  },
  {
    id: 'opening-organization',
    title: 'Organização — voxels se alinhando',
    start: 0.08,
    end: 0.14,
    cameraPath: 'slow-approach',
    activeObjects: ['fragments', 'nucleus', 'wave-organize', 'voxels'],
    quality: 'high',
    reducedMotionFallback: 'skip',
    color: '#3b82f6',
    intensity: 0.8,
  },
  {
    id: 'nucleus-formation',
    title: 'Núcleo SGS — materialização por voxels',
    start: 0.14,
    end: 0.20,
    cameraPath: 'idle-front',
    activeObjects: ['nucleus', 'fragments', 'laptop', 'dashboard', 'voxels'],
    quality: 'high',
    reducedMotionFallback: 'show-static',
    color: '#06b6d4',
    intensity: 0.9,
  },
  {
    id: 'scanner-risk',
    title: 'Scanner de risco — varredura dos módulos',
    start: 0.25,
    end: 0.35,
    cameraPath: 'scan-move',
    activeObjects: ['laptop', 'dashboard', 'scanner', 'cards', 'frozen-time'],
    quality: 'high',
    reducedMotionFallback: 'show-static',
    color: '#f59e0b',
    intensity: 0.7,
  },
  {
    id: 'critical-analysis',
    title: 'Momento de Análise Crítica — tempo congelado',
    start: 0.30,
    end: 0.38,
    cameraPath: 'freeze-approach',
    activeObjects: ['scanner', 'cards', 'frozen-time', 'analysis'],
    quality: 'ultra',
    reducedMotionFallback: 'show-static',
    color: '#ef4444',
    intensity: 1.0,
  },
  {
    id: 'protection-field',
    title: 'Campo de proteção — escudo digital',
    start: 0.38,
    end: 0.48,
    cameraPath: 'orbit-right',
    activeObjects: ['laptop', 'shield', 'cards', 'spatial-warp'],
    quality: 'high',
    reducedMotionFallback: 'show-static',
    color: '#22c55e',
    intensity: 0.8,
  },
  {
    id: 'spatial-deformation',
    title: 'Deformação espacial — entrada no sistema',
    start: 0.35,
    end: 0.45,
    cameraPath: 'warp-approach',
    activeObjects: ['shield', 'spatial-warp'],
    quality: 'ultra',
    reducedMotionFallback: 'skip',
    color: '#3b82f6',
    intensity: 0.6,
  },
  {
    id: 'document-construction',
    title: 'Documento construído no ar',
    start: 0.50,
    end: 0.58,
    cameraPath: 'document-approach',
    activeObjects: ['document', 'particles'],
    quality: 'high',
    reducedMotionFallback: 'skip',
    color: '#3b82f6',
    intensity: 0.6,
  },
  {
    id: 'chain-reaction',
    title: 'Reação em cadeia — módulos integrados',
    start: 0.60,
    end: 0.70,
    cameraPath: 'orbit-left',
    activeObjects: ['cards', 'energy-lines', 'nucleus'],
    quality: 'high',
    reducedMotionFallback: 'show-static',
    color: '#06b6d4',
    intensity: 0.9,
  },
  {
    id: 'module-tunnel',
    title: 'Túnel dos módulos',
    start: 0.72,
    end: 0.82,
    cameraPath: 'tunnel-forward',
    activeObjects: ['tunnel', 'cards'],
    quality: 'high',
    reducedMotionFallback: 'skip',
    color: '#3b82f6',
    intensity: 0.7,
  },
  {
    id: 'through-screen',
    title: 'Atravessando a tela — entrada no sistema',
    start: 0.70,
    end: 0.78,
    cameraPath: 'through-screen-approach',
    activeObjects: ['laptop', 'through-screen'],
    quality: 'ultra',
    reducedMotionFallback: 'show-static',
    color: '#06b6d4',
    intensity: 0.9,
  },
  {
    id: 'digital-city',
    title: 'Cidade digital da empresa',
    start: 0.78,
    end: 0.86,
    cameraPath: 'city-overview',
    activeObjects: ['city', 'connections'],
    quality: 'ultra',
    reducedMotionFallback: 'skip',
    color: '#22c55e',
    intensity: 0.6,
  },
  {
    id: 'future-prediction',
    title: 'Previsão e tendências',
    start: 0.84,
    end: 0.90,
    cameraPath: 'timeline-move',
    activeObjects: ['timeline', 'graphs'],
    quality: 'high',
    reducedMotionFallback: 'show-static',
    color: '#06b6d4',
    intensity: 0.5,
  },
  {
    id: 'cinematic-ending',
    title: 'Final — convergência ao núcleo',
    start: 0.92,
    end: 1.00,
    cameraPath: 'ending-pullback',
    activeObjects: ['nucleus', 'shield', 'cards', 'energy-lines'],
    quality: 'high',
    reducedMotionFallback: 'show-static',
    color: '#22c55e',
    intensity: 1.0,
  },
]

// Curvas de câmera (pontos de controle para Catmull-Rom)
export const cameraPaths: Record<string, [number, number,number][]> = {
  'idle-front': [
    [0, 0.8, 4.2],
    [0, 0.8, 4.2],
  ],
  'slow-approach': [
    [0, 0.8, 4.2],
    [0, 0.6, 3.6],
    [0, 0.5, 3.2],
  ],
  'scan-move': [
    [0, 0.8, 4.2],
    [1.2, 0.6, 3.8],
    [0, 0.4, 3.4],
    [-1.2, 0.6, 3.8],
    [0, 0.8, 4.2],
  ],
  'orbit-right': [
    [0, 0.8, 4.2],
    [1.5, 0.6, 3.5],
    [0.8, 0.4, 3.0],
    [0, 0.5, 3.2],
  ],
  'orbit-left': [
    [0, 0.8, 4.2],
    [-1.5, 0.6, 3.5],
    [-0.8, 0.4, 3.0],
    [0, 0.5, 3.2],
  ],
  'document-approach': [
    [0, 0.8, 4.2],
    [0.3, 0.5, 3.0],
    [0.5, 0.3, 2.2],
    [0, 0.4, 2.5],
  ],
  'tunnel-forward': [
    [0, 0.8, 4.2],
    [0, 0.6, 2.0],
    [0, 0.4, 0.5],
    [0, 0.2, -1.0],
  ],
  'city-overview': [
    [0, 0.8, 4.2],
    [1.0, 1.5, 5.0],
    [0, 2.0, 4.5],
    [-0.5, 1.5, 4.0],
  ],
  'timeline-move': [
    [0, 0.8, 4.2],
    [-1.0, 0.6, 3.8],
    [-2.0, 0.4, 3.5],
  ],
  'ending-pullback': [
    [0, 0.8, 4.2],
    [0, 1.0, 5.0],
    [0, 1.2, 6.0],
  ],
  'freeze-approach': [
    [0, 0.8, 4.2],
    [0.3, 0.5, 3.2],
    [0.5, 0.3, 2.0],
    [0.4, 0.2, 1.8],
  ],
  'warp-approach': [
    [0, 0.8, 4.2],
    [0.2, 0.6, 3.0],
    [0.5, 0.4, 2.0],
    [0, 0.3, 1.5],
  ],
  'through-screen-approach': [
    [0, 0.8, 4.2],
    [0, 0.6, 3.0],
    [0, 0.4, 2.0],
    [0, 0.3, 0.5],
  ],
}

// Núcleo de segurança — cores SGS institucionais
export const sgsCoreColors = {
  nucleus: '#06b6d4',
  primary: '#3b82f6',
  success: '#22c55e',
  warning: '#f59e0b',
  danger: '#ef4444',
  surface: '#1e3a5f',
  bg: '#071a33',
}
