import type { Module } from '@/types'

export const modules: Module[] = [
  {
    icon: 'Building2',
    name: 'Empresas',
    description: 'Cadastro e gestão de múltiplas empresas com dados completos de SST.',
    category: 'Gestão',
    href: '#',
  },
  {
    icon: 'Users',
    name: 'Colaboradores',
    description: 'Controle completo de funcionários, exames, treinamentos e documentos.',
    category: 'Gestão',
    href: '#',
  },
  {
    icon: 'KeyRound',
    name: 'Usuários e permissões',
    description: 'Controle de acesso com perfis personalizados para cada tipo de usuário.',
    category: 'Segurança',
    href: '#',
  },
  {
    icon: 'FileText',
    name: 'DDS',
    description: 'Registro e gestão do Diário de Discussão de Segurança com histórico completo.',
    category: 'Documentos',
    href: '#',
  },
  {
    icon: 'ClipboardCheck',
    name: 'APR',
    description: 'Análise Preliminar de Riscos integrada com planos de ação.',
    category: 'Documentos',
    href: '#',
  },
  {
    icon: 'Search',
    name: 'Inspeções',
    description: 'Inspeções de segurança com checklists personalizáveis e relatórios automáticos.',
    category: 'Gestão',
    href: '#',
  },
  {
    icon: 'FolderOpen',
    name: 'Documentos',
    description: 'Repositório centralizado para todos os documentos de SST da empresa.',
    category: 'Documentos',
    href: '#',
  },
  {
    icon: 'GraduationCap',
    name: 'Treinamentos',
    description: 'Gestão de treinamentos, certificados e controle de validade.',
    category: 'Gestão',
    href: '#',
  },
  {
    icon: 'Target',
    name: 'Planos de ação',
    description: 'Criação e acompanhamento de planos de ação com prazos e responsáveis.',
    category: 'Gestão',
    href: '#',
  },
  {
    icon: 'AlertTriangle',
    name: 'Gestão de riscos',
    description: 'Identificação, avaliação e controle de riscos ocupacionais.',
    category: 'Segurança',
    href: '#',
  },
  {
    icon: 'PieChart',
    name: 'Relatórios',
    description: 'Relatórios profissionais e personalizáveis para tomada de decisão.',
    category: 'Analytics',
    href: '#',
  },
  {
    icon: 'LayoutDashboard',
    name: 'Dashboard',
    description: 'Painel completo com indicadores em tempo real da sua gestão de SST.',
    category: 'Analytics',
    href: '#',
  },
  {
    icon: 'BellRing',
    name: 'Notificações',
    description: 'Alertas inteligentes sobre vencimentos, prazos e eventos importantes.',
    category: 'Comunicação',
    href: '#',
  },
]
